### ISSUE TITLE
Current target does not support NodeJS v4

### ISSUE THREAD

**Issue by samvv** [TypeForce/tsdoc#34]
```
/home/travis/build/TypeForce/tsdoc/lib/bin/tsdoc.js:28
        const { options, errors } = ts.parseCommandLine(argv['--'] || []);
              ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```
We either need to downgrade the TypeScript target, or require NodeJS LTS above v6.

**Comment by samvv** [comment]
I've temporarily removed the `v4` target from the Travis build in #33. Asking @BurtHarris to confirm if this is OK.

**Comment by BurtHarris** [comment]
@samvv, I'm fine with removing node@4 support.
